<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-3EH4CFI" failures="0" tests="11" name="com.tutorialsninja.qa.testcases.LoginTest" time="159.306" errors="3" timestamp="2023-11-24T16:23:45 IST" skipped="0">
  <testcase classname="com.tutorialsninja.qa.testcases.LoginTest" name="SetterGetterMethods" time="18.858"/>
  <system-out/>
  <testcase classname="com.tutorialsninja.qa.testcases.LoginTest" name="Failed_verifyLoginWithValidCresentials" time="11.365">
    <error message="Cannot invoke &quot;com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)&quot; because &quot;com.tutorialsninja.qa.listeners.QAListeners.extentTest&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)" because "com.tutorialsninja.qa.listeners.QAListeners.extentTest" is null
at com.tutorialsninja.qa.listeners.QAListeners.printLog(QAListeners.java:96)
at com.tutorialsninja.qa.testcases.LoginTest.Failed_verifyLoginWithValidCresentials(LoginTest.java:62)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
    </error>
  </testcase> <!-- Failed_verifyLoginWithValidCresentials -->
  <system-out/>
  <testcase classname="com.tutorialsninja.qa.testcases.LoginTest" name="verifyLoginWithValidCresentials" time="14.367">
    <error message="Cannot invoke &quot;com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)&quot; because &quot;com.tutorialsninja.qa.listeners.QAListeners.extentTest&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)" because "com.tutorialsninja.qa.listeners.QAListeners.extentTest" is null
at com.tutorialsninja.qa.listeners.QAListeners.printLog(QAListeners.java:96)
at com.tutorialsninja.qa.testcases.LoginTest.verifyLoginWithValidCresentials(LoginTest.java:49)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
    </error>
  </testcase> <!-- verifyLoginWithValidCresentials -->
  <system-out/>
  <testcase classname="com.tutorialsninja.qa.testcases.LoginTest" name="verifyLoginWithInvalidCredentials" time="23.890"/>
  <system-out/>
  <testcase classname="com.tutorialsninja.qa.testcases.LoginTest" name="verifyLoginWithInvalidEmailAndValidPassword" time="10.783"/>
  <system-out/>
  <testcase classname="com.tutorialsninja.qa.testcases.LoginTest" name="verifyLoginWith_ValidEmailAnd_InvalidPassword" time="11.425"/>
  <system-out/>
  <testcase classname="com.tutorialsninja.qa.testcases.LoginTest" name="verifyLoginWith_ValidEmailAnd_InvalidPassword1" time="9.474"/>
  <system-out/>
  <testcase classname="com.tutorialsninja.qa.testcases.LoginTest" name="verifyLoginWith_ValidEmailAnd_InvalidPassword1" time="15.567"/>
  <system-out/>
  <testcase classname="com.tutorialsninja.qa.testcases.LoginTest" name="verifyLoginWith_ValidEmailAnd_InvalidPassword1" time="11.847">
    <error message="Keys to send should be a not null CharSequence" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: Keys to send should be a not null CharSequence
at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:98)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:52)
at jdk.proxy2/jdk.proxy2.$Proxy16.sendKeys(Unknown Source)
at com.tutorialsninja.qa.pages.LoginPage.LoginEmailPasswordClickLogin(LoginPage.java:29)
at com.tutorialsninja.qa.testcases.LoginTest.verifyLoginWith_ValidEmailAnd_InvalidPassword1(LoginTest.java:93)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
    </error>
  </testcase> <!-- verifyLoginWith_ValidEmailAnd_InvalidPassword1 -->
  <system-out/>
  <testcase classname="com.tutorialsninja.qa.testcases.LoginTest" name="verifyLoginWith_ValidEmailAnd_InvalidPassword1" time="11.894"/>
  <system-out/>
  <testcase classname="com.tutorialsninja.qa.testcases.LoginTest" name="verifyLoginWith_ValidEmailAnd_InvalidPassword1" time="19.836"/>
  <system-out/>
</testsuite> <!-- com.tutorialsninja.qa.testcases.LoginTest -->
